import { Providers } from "@/chakra/Providers";
import SideBarWithHeader from "./components/SideBar/SideBarWithHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <SideBarWithHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
